name: connection_notifier
description: A Flutter package that notifies when no internet connection as well as providing simple tools that help tracking the internet connection status.
version: 2.0.1
homepage: https://github.com/AmrAbdelmagid/connection_notifier

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  rxdart: 0.28.0
  flutter:
    sdk: flutter
  internet_connection_checker: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

